version: '3'
services:
  hotel_postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hotel_db
    ports:
      - '5432:5432'