spring:
  datasource:
    url: jdbc:postgresql://hotel-network:5432/hotel_db
    driver-class-name: org.postgresql.Driver
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true