-- liquibase formatted sql

-- changeset senty:1740049346574-1
-- comment: Создание таблицы отелей
CREATE TABLE hotel
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(128)                            NOT NULL,
    description     VARCHAR(4096),
    brand           VARCHAR(128)                            NOT NULL,
    address_id      BIGINT                                  NOT NULL,
    contacts_id     BIGINT                                  NOT NULL,
    arrival_time_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_hotel PRIMARY KEY (id),
    FOREIGN KEY (address_id) REFERENCES address (id) ON DELETE CASCADE,
    FOREIGN KEY (contacts_id) REFERENCES contacts (id) ON DELETE CASCADE,
    FOREIGN KEY (arrival_time_id) REFERENCES arrival_time (id) ON DELETE CASCADE
);

-- changeset senty:1740049346574-2
-- comment: Создание таблицы для связи hotel-amenities
CREATE TABLE hotel_amenity
(
    amenity_id BIGINT NOT NULL,
    hotel_id   BIGINT NOT NULL,
    CONSTRAINT pk_hotel_amenity PRIMARY KEY (amenity_id, hotel_id),
    FOREIGN KEY (hotel_id) REFERENCES hotel (id) ON DELETE CASCADE,
    FOREIGN KEY (amenity_id) REFERENCES amenity (id) ON DELETE CASCADE
);