-- liquibase formatted sql

-- changeset senty:1740048697046-1
-- comment: Создание таблицы контактов
CREATE TABLE contacts
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    phone VARCHAR(32)                             NOT NULL,
    email VARCHAR(64)                             NOT NULL,
    CONSTRAINT pk_contacts PRIMARY KEY (id)
);

