-- liquibase formatted sql

-- changeset senty:1740047745171-1
-- comment: Создание таблицы адресов
CREATE TABLE address
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    house_number INTEGER                                 NOT NULL,
    street       VARCHAR(128)                            NOT NULL,
    city         VARCHAR(64)                             NOT NULL,
    country      VARCHAR(64)                             NOT NULL,
    post_code    VARCHAR(32)                             NOT NULL,
    CONSTRAINT pk_address PRIMARY KEY (id)
);

