-- liquibase formatted sql

-- changeset senty:1740049154815-1
-- comment: Создание таблицы удобств
CREATE TABLE amenity
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(64)                             NOT NULL,
    CONSTRAINT pk_amenity PRIMARY KEY (id),
    CONSTRAINT uc_amenity_name UNIQUE (name)
);
